---
name: foxy-single-sign-on-config
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Dynamic\Foxy\SingleSignOn\Extension\FoxySingleSignOnExtension

Dynamic\Foxy\Parser\Controller\FoxyController:
  extensions:
    - Dynamic\Foxy\SingleSignOn\Extension\FoxyControllerMemberExtension
