---
name: foxy-single-sign-on-routes
after:
  - '#rootroutes'
  - '#coreroutes'
---

SilverStripe\Control\Director:
  rules:
    'foxysso': 'Dynamic\Foxy\SingleSignOn\Controller\SingleSignOnController'
